// Generated by CoffeeScript 1.7.1
(function() {
  var Calendar, showLocations,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  showLocations = {
    1: "Granger Sky Theater",
    37: "Granger Sky Theater",
    38: "Granger Sky Theater",
    2: "Definiti Space Theater",
    3: "Johnson Star Theater",
    5: "Guided Tours"
  };

  $(document).ready(function() {
    var cal, show_active_conditions, time_shift, update_screen, update_show_times;
    cal = new Calendar();
    window.cal = cal;
    time_shift = parseInt(window.location.hash.replace("#", "")) || 0;
    update_show_times = (function(_this) {
      return function() {
        return cal.getShowTimes(function() {});
      };
    })(this);
    show_active_conditions = (function(_this) {
      return function(show, show_name) {
        var active;
        active = false;
        if (show.time.isAfter(moment().subtract("hours", time_shift)) && show.available > 0) {
          active = true;
        }
        if (show_name.indexOf("Up?") > 0) {
          active = false;
        }
        return active;
      };
    })(this);
    update_screen = (function(_this) {
      return function() {
        var allowed_event_types, show, show_name, shows, showsList, theater, theaterDiv, theater_id, theater_name, times, _results;
        showsList = cal.showTimesForDay(moment());
        allowed_event_types = [1, 3, 37, 38];
        for (theater_id in showLocations) {
          theater_name = showLocations[theater_id];
          theaterDiv = $("#" + (theater_name.split(" ")[0].toLowerCase()) + "_shows");
          theaterDiv.html("");
        }
        _results = [];
        for (show_name in showsList) {
          shows = showsList[show_name];
          if (!(shows.length > 0)) {
            continue;
          }
          console.log(show_name, shows);
          if (allowed_event_types.indexOf(shows[0].eventType) !== -1 && show_name.indexOf("Up?") === -1) {
            theater = showLocations[shows[0].theater];
            if (theater) {
              theaterDiv = $("#" + (theater.split(" ")[0].toLowerCase()) + "_shows");
              times = ((function() {
                var _i, _len, _ref, _results1;
                _ref = shows || [];
                _results1 = [];
                for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                  show = _ref[_i];
                  _results1.push("<span class=' time " + (show_active_conditions(show, show_name) ? "active" : "") + "' > " + (show.time.format('h:mm a')) + "</span>");
                }
                return _results1;
              })()).join(", ");
              if (times) {
                console.log(show_name, shows[0].thearter);
                _results.push(theaterDiv.append("<div class='show_container'> <p class='show'>" + show_name + "</p><p class='times'> " + times + " </p> " + (shows[0].theater === 37 ? '<p class="premier">Premier Show</p>' : "") + "</div>"));
              } else {
                _results.push(void 0);
              }
            } else {
              _results.push(void 0);
            }
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      };
    })(this);
    update_show_times();
    setInterval(update_show_times, 20000);
    return setInterval(update_screen, 1000);
  });

  Calendar = (function() {
    function Calendar() {
      this._compileTemplates = __bind(this._compileTemplates, this);
      this.getFocusDate = __bind(this.getFocusDate, this);
      this.getEventsByWeek = __bind(this.getEventsByWeek, this);
      this.openHours = __bind(this.openHours, this);
      this.isClosed = __bind(this.isClosed, this);
      this.labourDay = __bind(this.labourDay, this);
      this.memorialDay = __bind(this.memorialDay, this);
      this.session = __bind(this.session, this);
      this.dayType = __bind(this.dayType, this);
      this.getOpenHours = __bind(this.getOpenHours, this);
      this.todaysShowTimes = __bind(this.todaysShowTimes, this);
      this.showTimesForDay = __bind(this.showTimesForDay, this);
      this.gotShowTimes = __bind(this.gotShowTimes, this);
      this.getShowTimes = __bind(this.getShowTimes, this);
      this.updateEventsOverview = __bind(this.updateEventsOverview, this);
      this.updatePageTimes = __bind(this.updatePageTimes, this);
      this.render = __bind(this.render, this);
    }

    Calendar.prototype.render = function() {
      var week;
      week = this.getFocusDate().isoWeek();
      return this.el.html(this.cTemplates['week']({
        week: week,
        events: this.eventsByWeek[week] || []
      }));
    };

    Calendar.prototype.updatePageTimes = function() {
      var cafeHours, hours, shopHours, weekdayHours, weekendHours;
      hours = this.getOpenHours();
      weekdayHours = this.openHours().hours[this.session()].weekday;
      weekendHours = this.openHours().hours[this.session()].weekend;
      if (hours !== "closed") {
        shopHours = "" + hours.shopOpen + " - " + hours.shopClose;
        cafeHours = "" + hours.cafeOpen + " - " + hours.cafeClose;
        hours = "" + hours.open + " - " + hours.close;
      } else {
        shopHours = 'closed';
        cafeHours = 'closed';
      }
      weekendHours = "" + weekendHours.open + " - " + weekendHours.close;
      weekdayHours = "" + weekdayHours.open + " - " + weekdayHours.close;
      $(".hours .today span").html(hours);
      $(".hours .weekday span").html(weekdayHours);
      $(".hours .weekend span").html(weekendHours);
      $("#top-bar li.museum span").html(hours);
      $("#top-bar li.cafe span").html(cafeHours);
      return $("#top-bar li.shop span").html(shopHours);
    };

    Calendar.prototype.updateEventsOverview = function() {
      var e, events, html, todaysEvents, tomorrowsEvents;
      events = this.squarespaceEvents.upcoming || [];
      todaysEvents = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = events.length; _i < _len; _i++) {
          e = events[_i];
          if (moment(e.startDate).isSame(moment(), 'day')) {
            _results.push(e);
          }
        }
        return _results;
      })();
      tomorrowsEvents = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = events.length; _i < _len; _i++) {
          e = events[_i];
          if (moment(e.startDate).isSame(moment().add(1, 'day'), 'day')) {
            _results.push(e);
          }
        }
        return _results;
      })();
      if (todaysEvents && todaysEvents.length > 0) {
        html = this.cTemplates['overview']({
          today: todaysEvents,
          tomorrow: tomorrowsEvents
        });
      } else {
        html = 'There are no events scheduled.';
      }
      return $('#events-overview').html(html);
    };

    Calendar.prototype.getShowTimes = function(cb) {
      if (cb == null) {
        cb = null;
      }
      return $.ajax({
        dataType: "json",
        url: "" + window.location.protocol + "//s3.amazonaws.com/adler-cache/show_times.json",
        timeout: 10000,
        success: (function(_this) {
          return function(times) {
            var extra_times, show, _ref;
            _this.showTimes = times;
            _ref = window.extra_shows;
            for (show in _ref) {
              extra_times = _ref[show];
              _this.showTimes[show] = extra_times;
            }
            _this.gotShowTimes();
            if (cb != null) {
              return cb();
            }
          };
        })(this),
        error: (function(_this) {
          return function() {
            _this.showTimes || (_this.showTimes = []);
            if (cb != null) {
              return cb();
            }
          };
        })(this)
      });
    };

    Calendar.prototype.gotShowTimes = function() {
      var show, time, times, _ref, _results;
      this.showTimes["Maravilla Cósmica"] = [];
      _ref = this.showTimes;
      _results = [];
      for (show in _ref) {
        times = _ref[show];
        times = (function() {
          var _i, _len, _results1;
          _results1 = [];
          for (_i = 0, _len = times.length; _i < _len; _i++) {
            time = times[_i];
            _results1.push({
              time: moment(time.StartDateTime, "MMM DD YYYY HH:mm:ss:SSSA").local(),
              available: time.Available,
              theater: time.ResourceID,
              eventType: time.EventTypeID
            });
          }
          return _results1;
        })();
        this.showTimes[show] = times;
        _results.push(window.showtimes = this.showTimes);
      }
      return _results;
    };

    Calendar.prototype.showTimesForDay = function(day) {
      var dayTimes, show, time, times, _ref;
      dayTimes = {};
      _ref = this.showTimes;
      for (show in _ref) {
        times = _ref[show];
        dayTimes[show] = (function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = times.length; _i < _len; _i++) {
            time = times[_i];
            if (time.time.isSame(day, 'day')) {
              _results.push(time);
            }
          }
          return _results;
        })();
      }
      return dayTimes;
    };

    Calendar.prototype.todaysShowTimes = function() {
      return this.todaysTimes = this.showTimesForDay(moment());
    };

    Calendar.prototype.getOpenHours = function() {
      var dayType, hours, result, session;
      if (this.isClosed()) {
        return result = 'closed';
      } else {
        hours = this.openHours().hours;
        session = this.session();
        dayType = this.dayType();
        return hours[session][dayType];
      }
    };

    Calendar.prototype.dayType = function() {
      if (moment().day() === 0 || moment().day() === 6) {
        return 'weekend';
      } else {
        return 'weekday';
      }
    };

    Calendar.prototype.session = function() {
      if (moment().isAfter(this.memorialDay()) && moment().isBefore(this.labourDay())) {
        return "late";
      } else {
        return "normal";
      }
    };

    Calendar.prototype.memorialDay = function(year) {
      var lastMonday, may;
      if (year == null) {
        year = null;
      }
      year || (year = moment().year());
      may = moment("" + year + " 5 31");
      if (may.day() === 1) {
        lastMonday = june;
      } else if (may.day() === 0) {
        lastMonday = may.subtract(6, "days");
      } else {
        lastMonday = may.subtract(may.day() - 1, 'days');
      }
      return lastMonday;
    };

    Calendar.prototype.labourDay = function(year) {
      var firstMonday, september;
      if (year == null) {
        year = null;
      }
      year || (year = moment().year());
      september = moment("" + year + " 9 1");
      if (september.day() === 1) {
        firstMonday = september;
      } else if (september.day() === 0) {
        firstMonday = september.add(1, "day");
      } else {
        firstMonday = september.add(8 - september.day(), 'days');
      }
      return firstMonday;
    };

    Calendar.prototype.isClosed = function() {
      var closedDay, today, _i, _len, _ref;
      today = moment();
      _ref = this.openHours().closed;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        closedDay = _ref[_i];
        if (today.date() === moment(closedDay).date() && today.month() === moment(closedDay).month()) {
          return true;
        }
      }
      return false;
    };

    Calendar.prototype.openHours = function() {
      return {
        hours: {
          late: {
            weekday: {
              open: "9:30 am",
              close: "6 pm",
              cafeOpen: "10 am",
              cafeClose: "3 pm",
              shopOpen: "9:30 am",
              shopClose: "6 pm"
            },
            weekend: {
              open: "9:30 am",
              close: "6 pm",
              cafeOpen: "10 am",
              cafeClose: "3:30 pm",
              shopOpen: "9:30 am",
              shopClose: "6 pm"
            }
          },
          normal: {
            weekday: {
              open: "9:30 am",
              close: "6 pm",
              cafeOpen: "10 am",
              cafeClose: "3 pm",
              shopOpen: "9:30 am",
              shopClose: "6 pm"
            },
            weekend: {
              open: "9:30 am",
              close: "6 pm",
              cafeOpen: "10 am",
              cafeClose: "3:30 pm",
              shopOpen: "9:30 am",
              shopClose: "6 pm"
            }
          }
        },
        closed: ["25th December", "28 November"]
      };
    };

    Calendar.prototype.getEventsByWeek = function(events, cb) {
      var day, e, week, _i, _len;
      this.eventsByWeek = {};
      for (_i = 0, _len = events.length; _i < _len; _i++) {
        e = events[_i];
        if (e.startDate != null) {
          week = moment(e.startDate).isoWeek();
          day = moment(e.startDate).day();
          if (this.eventsByWeek[week] == null) {
            this.eventsByWeek[week] = {};
          }
          if (this.eventsByWeek[week][day] == null) {
            this.eventsByWeek[week][day] = [];
          }
          this.eventsByWeek[week][day].push(e);
        }
      }
      if (cb != null) {
        return cb();
      }
    };

    Calendar.prototype.getFocusDate = function() {
      return this.focusDate || (this.focusDate = moment());
    };

    Calendar.prototype._compileTemplates = function() {
      var templateName, text, _ref, _results;
      this.cTemplates = {};
      _ref = this.templates;
      _results = [];
      for (templateName in _ref) {
        text = _ref[templateName];
        _results.push(this.cTemplates[templateName] = _.template(text));
      }
      return _results;
    };

    return Calendar;

  })();

  window.Calendar = Calendar;

}).call(this);
